### ISSUE TITLE
Local build failure on main branch

### ISSUE THREAD

**Issue by npetridis** [blocksecteam/metasuites#18]
Hello,

I have cloned locally the repo
Node version is v20.9.0 (I use mac os)
I ran `yarn install` successfully but when I try to run`yarn build:prod` I get the following error:

```
[vite]: Rollup failed to resolve import "@babel/runtime/helpers/esm/toConsumableArray" from ".yarn/__virtual__/antd-virtual-c06609172e/0/cache/antd-npm-5.14.2-58e1f90447-f894c67114.zip/node_modules/antd/es/cascader/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@babel/runtime/helpers/esm/toConsumableArray" from ".yarn/__virtual__/antd-virtual-c06609172e/0/cache/antd-npm-5.14.2-58e1f90447-f894c67114.zip/node_modules/antd/es/cascader/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/npetridis/projects/metasuites/.yarn/__virtual__/vite-virtual-0cd14955e8/0/cache/vite-npm-3.1.4-ed6d7fad7f-f3e532952b.zip/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:45908:19)
    at onwarn (file:///Users/npetridis/projects/metasuites/.yarn/__virtual__/vite-virtual-0cd14955e8/0/cache/vite-npm-3.1.4-ed6d7fad7f-f3e532952b.zip/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:45706:13)
    at Object.onwarn (file:///Users/npetridis/projects/metasuites/.yarn/cache/rollup-npm-2.78.1-25ffe2a567-9034814383.zip/node_modules/rollup/dist/es/shared/rollup.js:23225:13)
    at ModuleLoader.handleResolveId (file:///Users/npetridis/projects/metasuites/.yarn/cache/rollup-npm-2.78.1-25ffe2a567-9034814383.zip/node_modules/rollup/dist/es/shared/rollup.js:22352:26)
    at file:///Users/npetridis/projects/metasuites/.yarn/cache/rollup-npm-2.78.1-25ffe2a567-9034814383.zip/node_modules/rollup/dist/es/shared/rollup.js:22313:26
 ```

I did some searching but couldn't find any solution.

**Comment by cong1223** [comment]
Trying to modify the Node.js version to 18.17.0. Refer to https://github.com/blocksecteam/metasuites/blob/main/package.json. engines.node.
